### PR TITLE
Add label selector to secret watches/cache (Fix E2E issues)

### LINKED ISSUE #360: high memory utilization, crashes, in large openshift clusters
**What did you do to encounter the bug?**
- create 4k projects 
- install operator

**What did you expect?**
the operator will run without issue

**What happened instead?**
The operator pod continuously hit its memory limit and crashed. We increase the limit until it would run, eventually settling around 1.8gb. The operator was also slower to react to secret events.

**Screenshots**
image

**Operator Information**
 - 0.6.1

**Kubernetes Cluster Information**
 - Openshift
 - 4.9.8

**Additional context**
given that every new project creates 9 secrets by default, the amount of cached objects (some of them large in size) gets out of hand, e.g. 18k+ secrets.

### PR DESCRIPTION
**Pull request by chatton**
### All Submissions:

This PR adds to the changes made by @tchughesiv and updates our E2E tests and helm charts. A new label is required to watch secrets.

Note: The helm upgrade test is currently failing as there are manual steps needed (update existing secrets with this label). These will be added to the release notes for the next release.

closes #360

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).

### CODE REVIEW

File: test/e2e/cli/kubecli/kubecli.go [hunk 1]
```diff
@@ -128,9 +128,20 @@ func CreateUserSecret(name, ns string) {
 	)
 	result := cli.GetSessionExitMsg(session)
 	EventuallyWithOffset(1, result).Should(SatisfyAny(Say(name+" created"), Say("already exists")), "Can't create user secret"+name)
+
+	labels := map[string]string{
+		"atlas.mongodb.com/type": "credentials",
```
Comment (igor-karpukhin) [inline test/e2e/cli/kubecli/kubecli.go:133]: Since you added these values as const in `pkg/controller/connectionsecret/ensuresecret.go`, consider to use them instead of just strings here and down below.

File: test/e2e/cli/kubecli/kubecli.go [hunk 2]
```diff
@@ -139,6 +150,12 @@ func CreateApiKeySecret(keyName, ns string) { // TODO add ns
 	)
 	result := cli.GetSessionExitMsg(session)
 	EventuallyWithOffset(1, result).Should(SatisfyAny(Say(keyName+" created"), Say("already exists")), "Can't create secret"+keyName)
+
+	session = cli.ExecuteWithoutWriter("kubectl", "label", "secret", keyName, "atlas.mongodb.com/type=credentials", "-n", ns, "--overwrite")
```
Comment (leo-ri) [inline test/e2e/cli/kubecli/kubecli.go:154]: I guess here is safe to write to output (to use "cli.Execute" instead)

File: test/e2e/cli/kubecli/kubecli.go (hunk 1 above)
Comment (chatton) [reply test/e2e/cli/kubecli/kubecli.go:133]: yes good idea, will do this.

File: .gitignore [hunk 3]
```diff
@@ -32,3 +32,7 @@ event_*.json
 my-*
 tags
 testbin/
+
+# don't include generated files from e2e tests
+test/e2e/data/operator-*
+test/e2e/output/ns-operator*
```
Comment (leo-ri) [inline .gitignore:38]: I guess need include full test/e2e/output  (there could be be different prefixes)

**Comment by chatton** [comment]
@leo-ri @igor-karpukhin ready for another pass

File: test/e2e/cli/kubecli/kubecli.go [hunk 4]
```diff
@@ -128,9 +130,20 @@ func CreateUserSecret(name, ns string) {
...
 	result := cli.GetSessionExitMsg(session)
 	EventuallyWithOffset(1, result).Should(SatisfyAny(Say(name+" created"), Say("already exists")), "Can't create user secret"+name)
+
+	labels := map[string]string{
+		connectionsecret.TypeLabelKey: connectionsecret.CredLabelVal,
+	}
+
+	// apply all labels to the secret
+	for k, v := range labels {
+		session = cli.ExecuteWithoutWriter("kubectl", "label", "secret", name, fmt.Sprintf("%s=%s", k, v), "-n", ns, "--overwrite")
```
Comment (leo-ri) [inline test/e2e/cli/kubecli/kubecli.go:140]: this one is safe too (not so important)

**Review by leo-ri — APPROVED** [review]
